apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkfire-app
  namespace: testing
  labels:
    injectvars: "true"
spec:
  selector:
    matchLabels:
      injectvars: "true"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        injectvars: "true"
    spec:
      automountServiceAccountToken: false
      containers:
      - image: diegoparra/lf-app:dabb1f03d2e7ef89d69d3d1c88887b2b5fa08b8b
        imagePullPolicy: Always
        name: linkfire-app
        ports:
          - containerPort: 3000

        env:
          - name: LOG_LEVEL
            value: INFO
        resources:
          limits:
            cpu: 40m
            memory: 100Mi
          requests:
            cpu: 40m
            memory: 100Mi
