apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

namespace: testing

images:
- name: diegoparra/lf-app
  newName: diegoparra/lf-app
  newTag: 53c5b109d5f67b7f38c847bfa5781d84ff464b8b
